language: ruby
rvm:
  - 2.0.0
language: ruby
env:
  - REDMINE_VERSION=2.5.1 VERBOSE=yes
script:
  - export PLUGIN=redmine_gitlab_integration
  - export WORKSPACE=$(pwd)/workspace
  - export PATH_TO_PLUGIN=$(pwd)
  - export PATH_TO_REDMINE=$WORKSPACE/redmine
  - mkdir $WORKSPACE
  - bash -x ./.travis-init.sh -r || exit 1
  - bash -x ./.travis-init.sh -i || exit 1
  - bash -x ./.travis-init.sh -t || exit 1
  - bash -x ./.travis-init.sh -u || exit 1
